MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Services;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers;

public class MoviesController: Controller
{
    private readonly IMovieService _MovieService;
    private readonly ICurrentUser _currentUser;
    private readonly IUserService _userService;


    public MoviesController(IMovieService movieService, ICurrentUser currentUser, IUserService userService)
    {
        _MovieService = movieService;
        _currentUser = currentUser;
        _userService = userService;
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        ViewData["isPurchased"] = false;
        ViewData["isFavorited"] = false;
        ViewData["isReviewed"] = false;
        if (_currentUser.IsAuthenticated)
        {
            var currentUser = _currentUser.userId;
            var getMoviesPurchasesDetails = await _userService.GetPurchasesDetails(currentUser, id);
            if (getMoviesPurchasesDetails != null)
            {
                ViewData["isPurchased"] = true;
            }

            var isFavorited = await _userService.FavoriteExists(currentUser, id);
            if (isFavorited)
            {
                ViewData["isFavorited"] = true;
            }

            var isReviewed = await _userService.isReviewExistByUser(currentUser, id);
            if (isReviewed)
            {
                ViewData["isReviewed"] = true;
            }
        }
        var movieDetails = await _MovieService.GetMovieDetails(id);
        return View(movieDetails);
    }

    public async Task<IActionResult> Genres(int id, int pageSize = 30, int pageNumber = 1)
    {
        var pagedNumbers = await _MovieService.GetMoviesByGenres(id, pageSize, pageNumber);
        return View("PagedNumbers", pagedNumbers);
    }
}

MovieShopMVC/Views/Shared/Reviews.cshtml
@model List<ApplicationCore.Models.ReviewModel>

@{
    foreach (var review in Model)
    {
        <div>
            <h3>User @review.UserId</h3>
            <p>Rating: @review.Rating</p>
            <p>Review: @review.ReviewText</p>
        </div>
    }
}

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MovieShopMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardModel
<div class="card mb-4">
    <a asp-action="Details" asp-controller="Movies" asp-route-id="@Model.Id">
        <img src="@Model.PosterURL" alt="@Model.Title" class="img-fluid"/>
    </a>    
</div>