MovieShopMVC/Controllers/CastController.cs
using ApplicationCore.Contracts.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers;

public class CastController: Controller
{
    private readonly ICastService _castService;

    public CastController(ICastService castService)
    {
        _castService = castService;
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var castDetails = await _castService.GetCastDetails(id);
        return View(castDetails);
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contracts.Services;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers;

public class MoviesController: Controller
{
    private readonly IMovieService _MovieService;
    private readonly ICurrentUser _currentUser;
    private readonly IUserService _userService;


    public MoviesController(IMovieService movieService, ICurrentUser currentUser, IUserService userService)
    {
        _MovieService = movieService;
        _currentUser = currentUser;
        _userService = userService;
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        ViewData["isPurchased"] = false;
        ViewData["isFavorited"] = false;
        ViewData["isReviewed"] = false;
        if (_currentUser.IsAuthenticated)
        {
            var currentUser = _currentUser.userId;
            var getMoviesPurchasesDetails = await _userService.GetPurchasesDetails(currentUser, id);
            if (getMoviesPurchasesDetails != null)
            {
                ViewData["isPurchased"] = true;
            }

            var isFavorited = await _userService.FavoriteExists(currentUser, id);
            if (isFavorited)
            {
                ViewData["isFavorited"] = true;
            }

            var isReviewed = await _userService.isReviewExistByUser(currentUser, id);
            if (isReviewed)
            {
                ViewData["isReviewed"] = true;
            }
        }
        var movieDetails = await _MovieService.GetMovieDetails(id);
        return View(movieDetails);
    }

    public async Task<IActionResult> Genres(int id, int pageSize = 30, int pageNumber = 1)
    {
        var pagedNumbers = await _MovieService.GetMoviesByGenres(id, pageSize, pageNumber);
        return View("PagedNumbers", pagedNumbers);
    }
}

MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers;

[Authorize]
public class UserController: Controller
{
    private readonly ICurrentUser _currentUser;
    private readonly IUserService _userService;
    public UserController(ICurrentUser currentUser, IUserService userService)
    {
        _currentUser = currentUser;
        _userService = userService;
    }
    

    [HttpGet]
    public async Task<IActionResult> Purchases()
    {

        var userId = _currentUser.userId;
        var purchases = await _userService.GetAllPurchasesForUser(userId);
        return View(purchases);
    }

    [HttpGet]
    public async Task<IActionResult> Favorites()
    {
        var userId = _currentUser.userId;
        var favorites = await _userService.GetAllFavoritesForUser(userId);
        return View(favorites);
    }

    [HttpGet]
    public async Task<IActionResult> Reviews(int movieId)
    {
        var userId = _currentUser.userId;
        var reviews = await _userService.GetAllReviewsByUser(movieId);
        return View("Reviews");
    }

    [HttpPost]
    public async Task<IActionResult> BuyMovie(PurchaseRequestModel model)
    {
        var userId = _currentUser.userId;
        var buy = await _userService.PurchaseMovie(model, userId);
        return Redirect($"~/Movies/Details/{model.MovieId}");
    }

    [HttpPost]
    public async Task<IActionResult> FavoriteMovie(int movieId)
    {
        var userId = _currentUser.userId;
        var favoriteMovie = await _userService.AddFavorite(new FavoriteRequestModel
        {
            UserId = userId,
            MovieId = movieId
        });
        return Redirect($"~/Movies/Details/{movieId}");
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UnfavoriteMovie(int id)
    {
        var userId = _currentUser.userId;
        var unfavoriteMovie = await _userService.RemoveFavorite(new FavoriteRequestModel
        {
            MovieId = id,
            UserId = userId
        });
        return Redirect($"~/Movies/Details/{id}");
    }

    [HttpPost]
    public async Task<IActionResult> ReviewMovie(ReviewRequestModel model)
    {
        
        var userId = _currentUser.userId;
        model.UserId = userId;
        var ReviewMovie = await _userService.AddMovieReview(model);
        return Redirect($"~/Movies/Details/{ReviewMovie.MovieId}");
        
    }

    [HttpPost, ActionName("DeleteReview")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteReviewByUser(int id)
    {
        var userId = _currentUser.userId;
        var remove = await _userService.DeleteMovieReview(id, userId);
        return Redirect($"~/Movies/Details/{id}");
    }
    [HttpGet]
    public async Task<IActionResult> EditReviews(int MovieId)
    {
        var userId = _currentUser.userId;
        var review = await _userService.GetReviewsByUserAndMovie(MovieId, userId);
        return View(review);
    }
    
    
    [HttpPost]
    public async Task<IActionResult> EditReview(ReviewRequestModel model)
    {
        if (ModelState.IsValid)
        {
            var userId = _currentUser.userId;
            model.UserId = userId;
            var edit = await _userService.UpdateMovieReview(model);
            return Redirect($"~/Movies/Details/{model.MovieId}");
        }

        return Redirect($"~/User/EditReviews?MovieId={model.MovieId}");
    }
}

MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsModel
<div class="row" style="background-image: linear-gradient( rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7) ), url(@Model.BackdropUrl); background-size: cover; height: 20rem">
    <div class="row">
        <div class="col-5">
            <img src="@Model.PosterUrl" style="padding-left: 20%;height: 20rem"/>
        </div>
        <div class="col-5">
            <h3 style="color: white">@Model.Title</h3>
            <p style="color: grey">@Model.Tagline</p>
            
            @{
                foreach (var genre in Model.Genres)
                {
                                                   
                    <span class="badge rounded-pill bg-secondary">
                        @genre.Name
                    </span>

                }
            }    
                        
            <p style="color: grey">
                @Model.RunTime m | @Model.ReleaseDate.Value.Year
            </p>
            <div>
                <span class="badge bg-success">8.9</span>
            </div>
            <p style="color: white">
                @Model.Overview
            </p>

        </div>
        <div class="col-2">
            <div class="d-grid gap-2" style="margin-top: 20%">
                @{
                    if ((bool) ViewData["isReviewed"])
                    {

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
                            <div class="modal-dialog modal-dialog-scrollable">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalToggleLabel">All Reviews</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <partial name="Reviews" model="Model.Reviews"/>
                                    </div>
                                    
                                    <div class="modal-footer">
                                        <a class="btn btn-primary" role="button" asp-controller="User" asp-action="EditReviews" asp-route-MovieId="@Model.Id">
                                            Edit my review
                                        </a>
                                        @using (Html.BeginForm("DeleteReview", "User", FormMethod.Post))
                                        {
                                            @Html.AntiForgeryToken()
                                            @Html.HiddenFor(model => model.Id)
                                            <button class="btn btn-dark" type="submit" class="btn btn-primary">Delete my review</button>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="btn btn-dark" data-bs-toggle="modal" href="#exampleModalToggle" role="button" style="background-color: transparent; text-align: center;color: white; border-color:  white">REVIEW</a>
                    }
                    else
                    {
                        <button class="btn btn-dark" style="background-color: transparent; text-align: center;color: white; border-color:  white" data-bs-toggle="modal" data-bs-target="#exampleModal3">
                            Review
                        </button>
                        <div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you want to review @Model.Title movie</p>
                                    </div>
                                    <form asp-controller="User" asp-action="ReviewMovie" method="post">
                                        <div class="form-group">
                                            <input name="MovieId" id="MovieId" class="form-control" readonly="readonly" value="@Model.Id" hidden="hidden"/>
                                        </div>
                                        <div class="form-group">
                                            <label for="Rating">Rating: </label>
                                            <input type="number" name="Rating" id="Rating" class="form-control" value="" required="required" step="0.01" min="0.01" max="9.9"/>

                                        </div>
                                        <div class="form-group">
                                             <label for="ReviewText">ReviewText: </label>
                                            <input type="text" name="ReviewText" id="ReviewText" class="form-control" value="" required="required"/>
                                        </div>


                                        <div class="form-group">
                                            <input class="btn btn-dark" type="submit" value="Review"/>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }
                }
                
                @{
                    if ((bool) ViewData["isPurchased"])
                    {
                        <button class="btn btn-dark" style="background-color: white; text-align: center;color: black;">Watch</button>
                    }
                    else
                    {
                        <button class="btn btn-dark" style="background-color: white; text-align: center;color: black;" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            BUY $@Model.Price
                        </button>
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure you want to buy @Model.Title movie
                                    </div>
                                    <form asp-controller="User" asp-action="BuyMovie" method="post">
                                        <div class="form-group">
                                            <input name="MovieId" id="MovieId" class="form-control" readonly="readonly" value="@Model.Id" hidden="hidden"/>
                                        </div>


                                        <div class="form-group">
                                            <input name="TotalPrice" id="TotalPrice" class="form-control" readonly="readonly" value="@Model.Price" hidden="hidden"/>

                                        </div>
                                        <div class="form-group">
                                            <input name="PurchaseDateTime" id="PurchaseDateTime" class="form-control" readonly="readonly" value="@DateTime.Today.ToString()" hidden="hidden"/>
                                        </div>
                                        <div class="form-group">
                                            <input name="PurchaseNumber" id="PurchaseNumber" class="form-control" readonly="readonly" value="@Guid.NewGuid()" hidden="hidden"/>
                                        </div>


                                        <div class="form-group">
                                            <input class="btn btn-dark" type="submit" value="Confirm"/>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                    }
                }

                @{
                    if (!(bool) ViewData["isFavorited"])
                    {
                        <form asp-controller="User" asp-action="FavoriteMovie" method="post">
                            <div class="form-group">
                                <input name="movieId" id="movieId" class="form-control" readonly="readonly" value="@Model.Id" hidden="hidden"/>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-dark" type="submit" class="btn btn-primary"><i class="fa fa-heart" style="font-size:48px"></i></button>
                            </div>
                        </form>
                    }
                    else
                    {
                        @using (Html.BeginForm("Delete", "User", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.Id)

                            <button class="btn btn-dark" type="submit" class="btn btn-primary"><i class="fa fa-heart" style="font-size:48px;color:red"></i></button>
                        }

                    }
                }

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-3" style="background-color: #f8f9fa">
        <h3>MOVIE FACTS</h3>
        <hr/>
        <div>
            <i class="fa fa-calendar"></i>
            <span>
                Release Date
            </span>
            <span class="badge rounded-pill bg-secondary">@Model.ReleaseDate.Value.Month @Model.ReleaseDate.Value.Day, @Model.ReleaseDate.Value.Year</span>    
        </div>
        <hr style="height: 2px; background-color: black"/>
        <div>
            <i class="fa fa-hourglass"></i>
            <span>
                Run Time
            </span>
            <span class="badge rounded-pill bg-secondary">@Model.RunTime m</span>       
        </div>
        <hr style="height: 2px; background-color: black"/>
        <div>
            <i class="far fa-money-bill-alt"></i>
            <span>
                Box Office
            </span>
            <span class="badge rounded-pill bg-secondary">$ @Model.Revenue</span>    
        </div>
        <hr style="height: 2px; background-color: black"/>
        <div>
            <i class="fas fa-dollar-sign"></i>
            <span>
                Budget
            </span>
            <span class="badge rounded-pill bg-secondary">$ @Model.Budget</span>    
        </div>
        
        <hr style="height: 2px; background-color: black"/>
        <div>
            <i class="fa fa-imdb"></i>
            <a href=@Model.ImdbUrl target="_blank" >
                <i class="fa fa-external-link"></i>
            </a>
        </div>
        <h3 style="margin-top: 10%">TRAILERS</h3>
        <hr/>
        @{
            foreach (var VARIABLE in Model.Trailers)
            {
                <div>
                    <a href=@VARIABLE.TrailerUrl style="color: black">
                        <i class="fa fa-youtube-play"></i>
                    </a>
                    <span>@VARIABLE.Name</span>
                </div>
                <hr style="height: 2px; background-color: black"/>
            }
        }
        
    </div>
    <div class="col-2">
        
    </div>
    <div class="col-7">
        <h3>CAST</h3>
        @{
            foreach (var cast in Model.Casts)
            {
                <a asp-action="Details" asp-controller="Cast" asp-route-id=@cast.Id>
                    <hr/>
                    <div class="row">
                                        
                        <div class="col-2">
                            <img class="img-fluid" src=@cast.ProfilePath alt=@cast.Name style="border-radius: 70%; height: 7rem" asp>
                        </div>
                        <div class="col-5">
                            <p>@cast.Name</p>
                        </div>
                        <div class="col-5">
                            <p>@cast.Character</p>
                        </div>
                    </div>
                    
                </a>
                
            }
        }
    </div>    
</div>

MovieShopMVC/Views/Movies/PagedNumbers.cshtml
@model ApplicationCore.Models.PagedResultSet<ApplicationCore.Models.MovieCardModel>
@{
}
@{
    <div class="rounded">
        <div class="container-fluid">
            <div class="row">
                @foreach (var movie in Model.Data)
                {
                
                    <div class="col-xl-2 col-sm-4 col-lg-3 col-6">
                        <partial name="_MovieCard" model="movie"/>

                    </div>
                }
            </div>
        </div>
    </div>
    
}
@{
    string togglePrevious = "page-item ";
    string toggleNext = "page-item ";
    if (!Model.HasPreviousPage)
    {
        togglePrevious += "disabled";
    }
    if (!Model.HasNextPage)
    {
        toggleNext += "disabled";
    }
    
    string valueNextPage = (Model.PageIndex + 1).ToString();
    string valueNextNextPage = (Model.PageIndex + 2).ToString();
    string currentPage = "?pageNumber=" + (Model.PageIndex).ToString();
    string nextPage = "?pageNumber=" + valueNextPage;
    string nextNextPage = "?pageNumber=" + valueNextNextPage;
    string leftTag = "?pageNumber=" + (Model.PageIndex - 1).ToString();
    string EndTag = "?pageNumber=" + (Model.TotalPages).ToString();
   
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="@togglePrevious"><a class="page-link" href="?pageNumber=1">&laquo;</a></li>
            <li class="@togglePrevious"><a class="page-link" href="@leftTag">&lt;</a></li>
            @{
                if (Model.PageIndex < Model.TotalPages - 3)
                {
                    <li class="page-item active"><a class="page-link" href="@currentPage">@Model.PageIndex</a></li>
                    <li class="page-item"><a class="page-link" href="@nextPage">@valueNextPage</a></li>
                    <li class="page-item"><a class="page-link" href="@nextNextPage">@valueNextNextPage</a></li>
                    <li class="page-item disabled"><a class="page-link" href="">...</a></li>
                    <li class="page-item"><a class="page-link" href="@EndTag">@Model.TotalPages</a></li>
                }
                else if (Model.PageIndex == Model.TotalPages - 3)
                {
                    <li class="page-item active"><a class="page-link" href="@currentPage">@Model.PageIndex</a></li>
                    <li class="page-item"><a class="page-link" href="@nextPage">@valueNextPage</a></li>
                    <li class="page-item"><a class="page-link" href="@nextNextPage">@valueNextNextPage</a></li>
                    <li class="page-item"><a class="page-link" href="@EndTag">@Model.TotalPages</a></li>
                }
                else if(Model.PageIndex == Model.TotalPages - 2)
                {
                    <li class="page-item active"><a class="page-link" href="@currentPage">@Model.PageIndex</a></li>
                    <li class="page-item"><a class="page-link" href="@nextPage">@valueNextPage</a></li>
                    <li class="page-item"><a class="page-link" href="@EndTag">@Model.TotalPages</a></li>
                }
                else if(Model.PageIndex == Model.TotalPages - 1)
                {
                    <li class="page-item active"><a class="page-link" href="@currentPage">@Model.PageIndex</a></li>
                    <li class="page-item"><a class="page-link" href="@EndTag">@Model.TotalPages</a></li>
                }
                else
                {
                    <li class="page-item"><a class="page-link" href="@EndTag">@Model.TotalPages</a></li>
                }
                
            }
            
            <li class="@toggleNext"><a class="page-link" href="@nextPage">&gt;</a></li>
            <li class="@toggleNext"><a class="page-link" href="@EndTag">&raquo;</a></li>
        </ul>
    </nav>    
}